@echo off
echo Setting up Meeting Helper...
echo Installing dependencies for user...
python -m pip install customtkinter pyaudiowpatch faster-whisper numpy requests moviepy pandas
echo Starting Application...
python main.py
pause
